### ISSUE TITLE
Placeholder should not be shown when disabled

### ISSUE THREAD

**Issue by Macadoshis** [fraywing/textAngular#1371]
When _text-angular_ has `ta-disabled="true"` and `placeholder` filled, the placeholder is shown on the readonly field.
The placeholder shouldn't be shown when the component is disabled.

My temporary workaround is to add following CSS in my webpage to hide the placeholder.

```css
*[text-angular][ta-disabled=true] *[placeholder] {
    display: none;
}
```

Please embed this behavior into the implementation :)
