### ISSUE TITLE
Images - odd behaviors

### ISSUE THREAD

**Issue by Hubrus** [fraywing/textAngular#562]
Sorry for being a pain in the .. but I've noticed several more issues :)

1. Centering an image doesn't work: http://screencast.com/t/zVnJ0gI9ufvP
2. Aligning an image to left/right, makes the control look odd: http://screencast.com/t/LswikZqdXy
3. Deleting an image by pressing delete key, not working
4. Clicking same image over and over again, toggles the image controls (and enables/disables textAngular control): http://screencast.com/t/TxS2RUsl1

**Comment by SimeonC** [comment]
OK, 1 and 2 are probably due to a bad choice of icons by me. The buttons are actually float-left, no-float and float right. To align an image use the actual text-alignment button at the top.

Haven't run into num 3 yet, though my keyboard doesn't have a delete key so unless it's an obvious fix I'm going to have trouble with that one.

4 - Yup, that's a weird bug!

Thanks for the video's, it helps make it clear!

**Comment by Hubrus** [comment]
Floating an image left or right, should not mess up the control's height. Probably a clear: both will fix the problem but I haven't try if it works.

**Comment by SimeonC** [comment]
Yes, a clear: both would work I think - though I'd copy over the clearfix code from bootstrap which is a bit more robust - it uses pseudo elements to apply the clear.

**Comment by JoelParke** [comment]
<p>I have fixed #4 and this will be included in 1.5.12 soon.<br/>see: https://github.com/fraywing/textAngular/commit/a3133cae14c59b9958c200f08ae0531eb91eeb34</p>

**Comment by wmai** [comment]
I used this CSS to fix it

``` css
// This will force the container to respect the height of all elements within it, regardless of floating elements
.ta-editor:after { 
    clear: both;
    content: '';
    display: block;
}
```
